# TODO: перевести комментарии на английский. Не то, что я не знаю английского, да и не то, что кто-то из англичан вообще узнает об этом плагине, просто было бы приятно.

hardcore-experiment:
  ==: ru.teasanctuary.hardcore_experiment.config.HardcoreExperimentConfig
  # Время, за которое эпоха угля автоматически переходит в эпоху меди
  # В секундах реального времени.
  coal-epoch-upgrade-timer: 180

  # Время, за которое игроки должны зайти в игру после создания мира, чтобы появиться не в качестве наблюдателя.
  # В секундах реального времени.
  initial-join-timer: 300

  # Время, которое даётся игрокам на возрождение товарища.
  # В секундах реального времени.
  respawn-timeout: 1200